### ISSUE TITLE
Redis::TimeSeries.madd fails when multiple keys are provided

### ISSUE THREAD

**Issue by fcbm** [dzunk/redis-time-series#71]
Steps to reproduce the issue:

```
$ docker run --network host --name redis -it -d --rm redislabs/redistimeseries:latest
$ docker exec -it redis redis-cli
127.0.0.1:6379> ts.create foo
OK
127.0.0.1:6379> ts.create bar
OK
```

```
$ docker run --rm --name ruby -it  --network host ruby:3-alpine /bin/sh
/ # gem install redis redis-time-series
Fetching redis-4.6.0.gem
Successfully installed redis-4.6.0
Fetching redis-time-series-0.7.0.gem
Successfully installed redis-time-series-0.7.0
2 gems installed
/ # irb
irb(main):001:0> require 'redis'
=> true
irb(main):002:0> require 'redis-time-series'
=> true
irb(main):003:0> Redis::TimeSeries.madd(foo: { 1 => 1234 }, bar: { 2 => 2345 })
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series/client.rb:47:in `redis')
/usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series/sample.rb:19:in `BigDecimal': can't convert nil into BigDecimal (TypeError)
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series/sample.rb:19:in `initialize'
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series.rb:115:in `new'
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series.rb:115:in `block (2 levels) in madd'
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series.rb:114:in `each'
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series.rb:114:in `each_with_index'
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series.rb:114:in `each'
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series.rb:114:in `map'
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series.rb:114:in `block in madd'
        from <internal:kernel>:124:in `then'
        from /usr/local/bundle/gems/redis-time-series-0.7.0/lib/redis/time_series.rb:113:in `madd'
        from (irb):3:in `<main>'
        from /usr/local/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /usr/local/bin/irb:25:in `load'
        from /usr/local/bin/irb:25:in `<main>'
 ```

The time series are updated, the error seems to be thrown when reply from redis is decoded
```
127.0.0.1:6379> ts.range foo - +
1) 1) (integer) 1
   2) 1234
127.0.0.1:6379> ts.range bar - +
1) 1) (integer) 2
   2) 2345
```

The same issue happens when issuing madd with multiple keys and timestamp/value pairs:
```
Redis::TimeSeries.madd(foo: { 1 => 1234, 10 => 12340 }, bar: { 2 => 2345, 20 => 23450 })
```

**Comment by dzunk** [comment]
Fix released in version 0.7.2
